apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-webapp.fullname" . }}-config
  labels:
    {{- include "nginx-webapp.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
        
        # Health check endpoint for .NET integration
        location /health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
        
        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }
    }